// Auri — TypeScript type definitions
// Core types used throughout the application

/**
 * Voice mask options for audio anonymization.
 */
export type VoiceMask =
  | 'warm'
  | 'robotic'
  | 'ethereal'
  | 'deep'
  | 'random';

/**
 * Status of a confession through its lifecycle.
 */
export type ConfessionStatus =
  | 'idle'
  | 'recording'
  | 'processing'
  | 'done';

/**
 * 3D environment presets for the booth scene.
 */
export type Environment =
  | 'classic'
  | 'forest'
  | 'rooftop';

/**
 * Status of the confession after processing.
 */
export type ConfessionProcessingStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed';

/**
 * A complete confession record returned from the API.
 */
export interface Confession {
  /** Unique confession identifier */
  id: string;
  /** Processing status */
  status: ConfessionProcessingStatus;
  /** The voice mask applied */
  voiceMask: VoiceMask;
  /** Whether the confession was posted anonymously */
  isAnonymous: boolean;
  /** Generated transcript (available after processing) */
  transcript: string | null;
  /** AI-generated summary (available after processing) */
  summary: string | null;
  /** URI to the masked audio file */
  maskedAudioUri: string | null;
  /** Duration of the recording in seconds */
  durationSeconds: number | null;
  /** ISO-8601 timestamp of when the confession was created */
  createdAt: string;
  /** ISO-8601 timestamp of last update */
  updatedAt: string;
}

/**
 * WebSocket message received from the server.
 * Server sends different event types during audio processing.
 */
export interface WebSocketMessage {
  /** Event type identifier */
  event: string;
  /** Event-specific payload */
  payload: Record<string, unknown>;
  /** ISO-8601 timestamp of the message */
  timestamp: string;
}

/**
 * Partial transcript update from WebSocket stream.
 */
export interface TranscriptPartial {
  /** Accumulated transcript text so far */
  text: string;
  /** Whether this is the final transcript */
  isFinal: boolean;
}

/**
 * Summary generated by AI after processing.
 */
export interface SummaryResult {
  /** The generated summary text */
  summary: string;
  /** Confidence score (0-1) */
  confidence: number;
}

/**
 * Mask processing status update from server.
 */
export interface MaskStatusUpdate {
  /** Current processing stage */
  stage: 'encoding' | 'masking' | 'synthesizing' | 'complete';
  /** Progress percentage (0-100) */
  progress: number;
}

/**
 * Error message from WebSocket or API.
 */
export interface ErrorMessage {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
}

/**
 * Audio recording state for the useAudioRecorder hook.
 */
export interface AudioRecordingState {
  /** Whether recording is currently active */
  isRecording: boolean;
  /** URI of the recorded audio file (available after stop) */
  audioUri: string | null;
  /** Duration of the recording in milliseconds */
  durationMs: number;
  /** Whether microphone permission has been granted */
  hasPermission: boolean | null;
  /** Error message if recording failed */
  error: string | null;
}

/**
 * WebSocket connection state.
 */
export type WebSocketConnectionState =
  | 'disconnected'
  | 'connecting'
  | 'connected'
  | 'reconnecting';
