"""Application configuration loaded from environment variables / .env file."""

from __future__ import annotations

import os

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Pydantic ``BaseSettings`` model for all Auri backend configuration.

    Values are read from environment variables first, falling back to a
    ``.env`` file in the working directory. ``AURI_ENV_FILE`` names a different
    file; set it empty to read no file at all (the test suite does, so a
    developer's ``.env`` cannot make a test pass that fails in CI).
    """

    model_config = SettingsConfigDict(
        env_file=os.environ.get("AURI_ENV_FILE", ".env") or None,
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
        # A refused value must not be echoed back: the error for a too-short
        # DEVICE_HASH_PEPPER would otherwise print fragments of it and of its neighbours.
        hide_input_in_errors=True,
    )

    # ── Database ──────────────────────────────────────────────────────────
    DB_HOST: str = "localhost"
    DB_PORT: int = 5432
    DB_NAME: str = "auri"
    DB_USER: str = "auri"
    DB_PASSWORD: str = ""
    DATABASE_URL: str = ""  # If set (e.g. by CI), overrides the DB_* parts above.

    # ── Security ──────────────────────────────────────────────────────────
    SECRET_KEY: str = "change-me-in-production"
    CORS_ORIGINS: str = "http://localhost:3000,http://localhost:8081"

    # ── Rate limiting ─────────────────────────────────────────────────────
    CONFESSION_RATE_LIMIT_SECONDS: int = 300  # 1 confession per 5 min (AGENTS.md §8.5)
    TTS_RATE_LIMIT_SECONDS: int = 10  # cost-abuse guard on POST /api/v1/tts
    STT_RATE_LIMIT_SECONDS: int = 10  # cost-abuse guard on POST /api/v1/stt
    VOICE_MASK_RATE_LIMIT_SECONDS: int = (
        10  # cost-abuse guard on POST /api/v1/voice/mask
    )
    # The header a reverse proxy in front of the backend sets to the client's address
    # (for example X-Real-IP from nginx), used for a per-address Guide limit (plan
    # 14.7). Empty, the default, means no proxy is trusted and no address limit runs.
    # Environment only: set it only when every request reaches the backend through
    # that proxy, and the proxy overwrites the header, or a client can choose it.
    TRUSTED_PROXY_HEADER: str = ""

    # ── HR analytics (Phase 11) ──────────────────────────────────────────
    # Smallest bucket size an aggregate may report. Anything smaller is
    # suppressed, because a 2-person chart identifies those 2 people.
    ANALYTICS_MIN_COHORT: int = 5

    # ── Data retention ────────────────────────────────────────────────────
    RETENTION_HOURS: int = 24  # purge forwarded/deleted confessions after this long
    # How long a reply is kept after it was written (>= 1: zero would delete every
    # reply the moment it is emptied).
    REPLY_RETENTION_DAYS: int = Field(default=30, ge=1)
    # How often the retention job is expected to run. The Privacy panel calls it
    # overdue once a run is older than this, and states that a confession can
    # therefore outlive RETENTION_HOURS by up to this long.
    RETENTION_EXPECTED_RUN_HOURS: int = Field(default=6, ge=1)

    # ── Crisis reply ──────────────────────────────────────────────────────
    # Contacts shown in the fixed crisis reply (confessions and priest mode). Never
    # generated by a model. All empty falls back to a compiled-in safe message.
    CRISIS_HELPLINE_NAME: str = ""
    CRISIS_HELPLINE_NUMBER: str = ""
    CRISIS_EAP_CONTACT: str = ""

    # ── Priest mode (Phase 13) ────────────────────────────────────────────
    # A grounded guide that answers from an Obsidian study vault. Off by default;
    # the flag is DB-editable so it doubles as a kill switch. Base URLs, the API key
    # and paths are environment only, so no dashboard edit can redirect questions.
    PRIEST_MODE_ENABLED: bool = False
    PRIEST_PERSONA_NAME: str = "Guide"
    # OpenAI-compatible chat server (vLLM). Empty falls back, for the prototype, to
    # the themes endpoint and its opt-ins (THEMES_LLM_*); never to a third-party API.
    PRIEST_LLM_BASE_URL: str = ""
    PRIEST_LLM_API_KEY: str = ""
    # The model name the chat server serves (for vLLM, exactly what /v1/models lists).
    # Empty uses THEMES_LLM_MODEL on the prototype shortcut; it is required when
    # PRIEST_LLM_BASE_URL is set.
    PRIEST_LLM_MODEL: str = ""
    PRIEST_LLM_ALLOW_INSECURE_HTTP: bool = False
    # Local Ollama used when the primary fails; empty derives it from OLLAMA_BASE_URL.
    PRIEST_FALLBACK_BASE_URL: str = ""
    PRIEST_FALLBACK_MODEL: str = ""
    PRIEST_LLM_TIMEOUT_SECONDS: int = Field(default=20, ge=1, le=120)
    PRIEST_TOTAL_DEADLINE_SECONDS: int = Field(default=30, ge=5, le=300)
    # Pinned from the retrieval evaluation (docs/priest-retrieval-report.md): bge-large
    # had the best not-covered F1 and hybrid MRR of the three installed embedders. A
    # different model needs its own index build and its own floors.
    PRIEST_EMBED_MODEL: str = "bge-large"
    PRIEST_TOP_K: int = Field(default=6, ge=1, le=12)
    # Relevance floors calibrated for bge-large on the 50-question gold set (13.12). The
    # earlier 0.5 and 3.0 called every question covered.
    PRIEST_MIN_RELEVANCE_DENSE: float = 0.547
    PRIEST_MIN_RELEVANCE_BM25: float = 18.8
    PRIEST_RATE_LIMIT_PER_MINUTE: int = Field(default=4, ge=1)
    PRIEST_RATE_LIMIT_PER_DAY: int = Field(default=40, ge=1)
    # Per client address, on top of the per-device limits, and only when
    # TRUSTED_PROXY_HEADER is set (plan 14.7). Wide because one office can share an
    # address.
    PRIEST_RATE_LIMIT_PER_IP_PER_MINUTE: int = Field(default=30, ge=1)
    PRIEST_RATE_LIMIT_PER_IP_PER_DAY: int = Field(default=1000, ge=1)
    PRIEST_MAX_CONCURRENCY: int = Field(default=4, ge=1, le=64)
    # JSON list of tradition ids; empty means all.
    PRIEST_TRADITIONS_ENABLED: str = ""
    PRIEST_VAULT_DIR: str = "/app/data/priest/vault"
    PRIEST_INDEX_DIR: str = "/app/data/priest/index"

    # ── Delivery ──────────────────────────────────────────────────────────
    # How many characters of a forwarded confession's transcript the backend hands
    # the Telegram bot (and so a department chat). 0 sends the summary only. The
    # Privacy panel states the live value.
    # Bounded so a message always fits Telegram's 4096-character limit; a refused
    # message would be retried on every poll, for ever.
    DELIVERY_TRANSCRIPT_CHARS: int = Field(default=1000, ge=0, le=2500)

    # ── Device code hardening ─────────────────────────────────────────────
    # A secret used to store each phone's code as an HMAC instead of as sent, so a
    # copy of the database cannot be presented as a phone. Empty keeps the old
    # behaviour (the Privacy panel says so). Losing or changing it strands every
    # phone's history and every unread HR reply, so keep it with the other secrets.
    DEVICE_HASH_PEPPER: str = ""

    # ── Speech-to-Text ────────────────────────────────────────────────────
    WHISPER_MODEL: str = "base"  # tiny / base / small / medium / large-v3
    STT_MAX_UPLOAD_BYTES: int = (
        25 * 1024 * 1024
    )  # 25MB, matches OpenAI Whisper API's cap
    # The longest recording the server accepts; the app stops at the same limit
    # (mobile MAX_RECORDING_DURATION_MS). Owner decision 2026-10-01: 5 minutes.
    MAX_RECORDING_SECONDS: int = Field(default=300, ge=1)

    # ── LLM ──────────────────────────────────────────────────────────────
    # Provider priority for LLMService(provider="auto"): Ollama, then Gemini,
    # then OpenAI — first provider to return a non-empty response wins.
    OLLAMA_BASE_URL: str = "http://localhost:11434"
    OLLAMA_MODEL: str = "llama3.2:3b"
    # Context window asked of Ollama. Every prompt here is short; without a cap Ollama
    # reserves memory for the model's whole context (a 3B model was seen holding 9.9 GB).
    OLLAMA_NUM_CTX: int = Field(default=4096, ge=512, le=131072)
    GEMINI_API_KEY: str = ""
    GEMINI_MODEL: str = "gemini-1.5-flash"
    OPENAI_API_KEY: str = ""
    # Optional OpenAI-compatible model (for example vLLM) for HR theme grouping,
    # used instead of local Ollama. Environment only: deliberately not editable
    # from the dashboard, so no one can silently repoint where summaries go.
    THEMES_LLM_BASE_URL: str = ""
    THEMES_LLM_MODEL: str = ""
    THEMES_LLM_API_KEY: str = ""
    # Send OPENAI_API_KEY to the themes server when THEMES_LLM_API_KEY is empty.
    # Off by default: that key is normally a real OpenAI credential and must not
    # go to another server unless the operator says so on purpose.
    THEMES_LLM_USE_OPENAI_API_KEY: bool = False
    # Assert that the themes server runs on this organisation's own infrastructure.
    # An address cannot prove it (an SSH tunnel to localhost can reach anywhere),
    # so the Privacy panel only says "own infrastructure" when told so.
    THEMES_LLM_SELF_HOSTED: bool = False
    # Plain http to a public address sends the key and summaries unencrypted;
    # refused unless this is set on purpose.
    THEMES_LLM_ALLOW_INSECURE_HTTP: bool = False
    THEMES_LLM_TIMEOUT_SECONDS: int = Field(default=120, ge=5, le=600)
    OPENAI_MODEL: str = "gpt-4o-mini"
    # Claude is explicit-provider-only (LLMService(provider="claude")) — not
    # part of the "auto" chain above.
    ANTHROPIC_API_KEY: str = ""
    ANTHROPIC_MODEL: str = "claude-3-5-sonnet-latest"

    # ── Telegram ──────────────────────────────────────────────────────────
    TELEGRAM_BOT_TOKEN: str = ""
    MODERATOR_TELEGRAM_CHAT_ID: str = ""  # flagged confessions relay here for review
    MODERATION_API_KEY: str = ""  # shared secret the bot uses to call /moderation/*
    DELIVERY_API_KEY: str = ""  # shared secret the bot uses to call /delivery/*
    METRICS_API_KEY: str = ""  # bearer token a Prometheus scrape job sends to /metrics

    # ── Admin dashboard (Phase 10, local dev) ───────────────────────────────
    ADMIN_API_KEY: str = (
        ""  # shared secret for the config/build dashboard's /admin/* routes
    )

    # ── Staff accounts (Phase 11) ───────────────────────────────────────────
    # First-admin bootstrap, read once at startup and only applied when the
    # users table is empty. Never hardcode values here (AGENTS.md §12);
    # leaving either blank disables bootstrap entirely.
    ADMIN_BOOTSTRAP_EMAIL: str = ""
    ADMIN_BOOTSTRAP_PASSWORD: str = ""

    # Session tokens for dashboard logins. SESSION_TOKEN_SECRET falls back to
    # SECRET_KEY when empty; signing refuses to run outside development while
    # that value is still the shipped placeholder.
    SESSION_TOKEN_SECRET: str = ""
    ACCESS_TOKEN_TTL_MINUTES: int = 30
    REFRESH_TOKEN_TTL_HOURS: int = 12
    LOGIN_MAX_ATTEMPTS: int = 5  # per email, before the window locks out
    LOGIN_ATTEMPT_WINDOW_SECONDS: int = 300

    # Single sign-on through any OpenID Connect provider (plan 15.10). All environment
    # only. Off unless the issuer, client id and secret, callback and dashboard URLs
    # are all set. Password login keeps working for accounts that have one. Accounts
    # are still created by an admin first: SSO links to an existing account by its
    # verified email and never creates one. MFA is the provider's job.
    OIDC_ISSUER: str = ""  # e.g. https://login.microsoftonline.com/<tenant>/v2.0
    OIDC_CLIENT_ID: str = ""
    OIDC_CLIENT_SECRET: str = ""
    # This backend's callback, registered with the provider:
    # https://<backend>/api/v1/auth/oidc/callback
    OIDC_REDIRECT_URI: str = ""
    # Where the dashboard is served; the callback hands the session over to it.
    OIDC_DASHBOARD_URL: str = ""
    OIDC_PROVIDER_LABEL: str = "Single sign-on"  # the login button's wording
    # First sign-in links by the ID token's email claim, which must be marked
    # verified. Some providers (Microsoft Entra) never send email_verified; turning
    # this off there trusts the provider's own email, so only do it for a provider
    # where users cannot set their own email address.
    OIDC_REQUIRE_EMAIL_VERIFIED: bool = True
    # Optional role mapping. With OIDC_ROLE_CLAIM set (for example "groups" or
    # "roles"), the provider decides the role at every sign-in through
    # OIDC_ROLE_MAP, a JSON object from claim value to admin, hr or moderator; an
    # account with no mapped value is refused. Empty keeps the role set in Auri.
    OIDC_ROLE_CLAIM: str = ""
    OIDC_ROLE_MAP: str = ""

    # ── LiveKit (Phase 7) ────────────────────────────────────────────────────
    # Self-hosted only — see docker-compose.yml's `livekit` service (--dev
    # mode). Defaults match that service's devkey/secret; LAN IP (not
    # localhost) is required for a real device to connect.
    LIVEKIT_URL: str = "ws://localhost:7880"
    LIVEKIT_API_KEY: str = "devkey"
    LIVEKIT_API_SECRET: str = "secret"

    # ── Recipient directory ──────────────────────────────────────────────
    DEPARTMENTS: str = "HR,Engineering,Management"  # comma-separated, admin-managed

    # ── Environment / Logging ─────────────────────────────────────────────
    ENVIRONMENT: str = "development"  # development | staging | production
    LOG_LEVEL: str = "INFO"
    SENTRY_DSN: str = ""  # empty disables Sentry entirely
    # Log every SQL statement with its parameters. Off by default, including in
    # development: the parameters are transcripts, summaries and reply text.
    SQL_ECHO: bool = False

    @model_validator(mode="after")
    def _pepper_is_strong_enough(self) -> Settings:
        """Refuse a short ``DEVICE_HASH_PEPPER`` instead of quietly using it.

        A guessable secret would leave the codes brute-forceable while the Privacy
        panel reported them as hardened.
        """
        if self.DEVICE_HASH_PEPPER and len(self.DEVICE_HASH_PEPPER) < 32:
            raise ValueError(
                "DEVICE_HASH_PEPPER must be at least 32 characters "
                "(generate one with: openssl rand -hex 32)"
            )
        return self

    @model_validator(mode="after")
    def _reply_outlives_confession(self) -> Settings:
        """Refuse a reply retention shorter than the confession's own.

        Otherwise a reply would be deleted before the row is ever emptied, and
        the reply-only shell would never exist.
        """
        if self.REPLY_RETENTION_DAYS * 24 < self.RETENTION_HOURS:
            raise ValueError(
                "REPLY_RETENTION_DAYS must cover at least RETENTION_HOURS "
                f"(got {self.REPLY_RETENTION_DAYS} days vs {self.RETENTION_HOURS} hours)"
            )
        return self


def parse_comma_separated_list(raw: str) -> list[str]:
    """Split a comma-separated settings value into a trimmed, non-empty list.

    Shared by ``CORS_ORIGINS`` and ``DEPARTMENTS`` parsing so both follow
    the same whitespace/empty-entry handling.
    """
    return [item.strip() for item in raw.split(",") if item.strip()]


settings = Settings()  # Singleton – import this everywhere.
